export const paperLibrary = [
  {
    id: "data-storage-1",
    sectionId: "data-storage",
    title: "The Log-Structured Merge-Tree (LSM-Tree)",
    authors: ["Patrick O'Neil", "Edward Cheng", "Dieter Gawlick", "Elizabeth O'Neil"],
    venue: "Acta Informatica",
    year: 1996,
    quality: "经典基础",
    categories: ["storage", "indexing"],
    link: "https://www.cs.umb.edu/~poneil/lsmtree.pdf",
    summary: "现代写优化存储引擎的源头之一，后来的 LevelDB、RocksDB 等系统都深受它影响。",
  },
  {
    id: "data-storage-2",
    sectionId: "data-storage",
    title: "Bigtable: A Distributed Storage System for Structured Data",
    authors: ["Fay Chang", "Jeffrey Dean", "Sanjay Ghemawat", "Wilson C. Hsieh"],
    venue: "OSDI",
    year: 2006,
    quality: "顶会",
    categories: ["distributed systems", "database"],
    link: "https://research.google/pubs/pub27898/",
    summary: "Google 的经典分布式存储系统论文，奠定了大规模结构化数据服务的工程范式。",
  },
  {
    id: "data-storage-3",
    sectionId: "data-storage",
    title: "Dynamo: Amazon's Highly Available Key-value Store",
    authors: ["Giuseppe DeCandia", "Deniz Hastorun", "Madan Jampani", "Gunavardhan Kakulapati"],
    venue: "SOSP",
    year: 2007,
    quality: "顶会",
    categories: ["key-value", "distributed systems"],
    link: "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf",
    summary: "高可用键值存储系统的代表作，对后来的 NoSQL 和云数据库设计影响极大。",
  },
  {
    id: "data-storage-4",
    sectionId: "data-storage",
    title: "Dremel: Interactive Analysis of Web-Scale Datasets",
    authors: ["Sergey Melnik", "Andrey Gubarev", "Jing Jing Long", "Geoffrey Romer"],
    venue: "VLDB",
    year: 2010,
    quality: "顶会",
    categories: ["analytics", "columnar"],
    link: "https://research.google/pubs/pub36632/",
    summary: "交互式大数据分析系统代表作，也是现代列式分析引擎思路的重要来源。",
  },
  {
    id: "data-storage-5",
    sectionId: "data-storage",
    title: "The FAISS Library",
    authors: ["Jeff Johnson", "Matthijs Douze", "Herve Jegou"],
    venue: "IEEE T-BD",
    year: 2021,
    quality: "高影响力",
    categories: ["vector search", "ANN"],
    link: "https://arxiv.org/abs/2401.08281",
    summary: "向量检索领域最常用的基础库之一，理解它有助于把握向量数据库背后的核心算法。",
  },
  {
    id: "data-storage-6",
    sectionId: "data-storage",
    title: "DiskANN: Fast Accurate Billion-point Nearest Neighbor Search on a Single Node",
    authors: ["Neelesh Gupta", "Leland Willard", "Xiangyao Yu", "Yuri N."],
    venue: "NeurIPS",
    year: 2019,
    quality: "高影响力",
    categories: ["vector search", "ANN"],
    link: "https://papers.nips.cc/paper_files/paper/2019/hash/09853c7fb1d3f8ee67a61b6bf4a7f8e6-Abstract.html",
    summary: "大规模向量检索的代表性工作，兼顾磁盘索引、精度和吞吐，工程价值非常高。",
  },

  {
    id: "computer-vision-1",
    sectionId: "computer-vision",
    title: "Deep Residual Learning for Image Recognition",
    authors: ["Kaiming He", "Xiangyu Zhang", "Shaoqing Ren", "Jian Sun"],
    venue: "CVPR",
    year: 2016,
    quality: "顶会",
    categories: ["image recognition", "backbone"],
    link: "https://arxiv.org/abs/1512.03385",
    summary: "ResNet 是现代视觉 backbone 的里程碑，理解它基本等于理解深层网络训练的拐点。",
  },
  {
    id: "computer-vision-2",
    sectionId: "computer-vision",
    title: "End-to-End Object Detection with Transformers",
    authors: ["Nicolas Carion", "Francisco Massa", "Gabriel Synnaeve", "Nicolas Usunier"],
    venue: "ECCV",
    year: 2020,
    quality: "顶会",
    categories: ["detection", "transformer"],
    link: "https://arxiv.org/abs/2005.12872",
    summary: "DETR 把 Transformer 正式带入目标检测，后来一系列视觉 transformer 检测器都和它有关。",
  },
  {
    id: "computer-vision-3",
    sectionId: "computer-vision",
    title: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale",
    authors: ["Alexey Dosovitskiy", "Lucas Beyer", "Alexander Kolesnikov", "Dirk Weissenborn"],
    venue: "ICLR",
    year: 2021,
    quality: "顶会",
    categories: ["vision transformer", "classification"],
    link: "https://arxiv.org/abs/2010.11929",
    summary: "ViT 是视觉 Transformer 主线论文，后续大量视觉基础模型都建立在这条路线之上。",
  },
  {
    id: "computer-vision-4",
    sectionId: "computer-vision",
    title: "Learning Transferable Visual Models From Natural Language Supervision",
    authors: ["Alec Radford", "Jong Wook Kim", "Chris Hallacy", "Aditya Ramesh"],
    venue: "ICML",
    year: 2021,
    quality: "顶会",
    categories: ["vision-language", "foundation model"],
    link: "https://arxiv.org/abs/2103.00020",
    summary: "CLIP 是视觉语言预训练的经典代表，也是今天多模态大模型非常重要的前序工作。",
  },
  {
    id: "computer-vision-5",
    sectionId: "computer-vision",
    title: "Segment Anything",
    authors: ["Alexander Kirillov", "Eric Mintun", "Nikhila Ravi", "Hanzi Mao"],
    venue: "ICCV",
    year: 2023,
    quality: "顶会",
    categories: ["segmentation", "foundation model"],
    link: "https://arxiv.org/abs/2304.02643",
    summary: "SAM 把分割推向基础模型化，是近年视觉领域最有代表性的高影响力工作之一。",
  },
  {
    id: "computer-vision-6",
    sectionId: "computer-vision",
    title: "DINOv2: Learning Robust Visual Features without Supervision",
    authors: ["Maxime Oquab", "Timothée Darcet", "Théo Moutakanni", "Huy V. Vo"],
    venue: "arXiv / Meta",
    year: 2023,
    quality: "高影响力",
    categories: ["self-supervised", "representation"],
    link: "https://arxiv.org/abs/2304.07193",
    summary: "近年非常强的视觉表示学习工作，实际应用和迁移能力都很突出。",
  },

  {
    id: "llm-memory-1",
    sectionId: "llm-memory",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    authors: ["Patrick Lewis", "Ethan Perez", "Aleksandra Piktus", "Fabio Petroni"],
    venue: "NeurIPS",
    year: 2020,
    quality: "顶会",
    categories: ["RAG", "retrieval"],
    link: "https://arxiv.org/abs/2005.11401",
    summary: "RAG 的奠基论文，今天绝大多数知识增强问答、企业知识库方案都能追溯到这篇。",
  },
  {
    id: "llm-memory-2",
    sectionId: "llm-memory",
    title: "Memorizing Transformers",
    authors: ["Yuhuai Wu", "Markus N. Rabe", "DeLesley Hutchins", "Christian Szegedy"],
    venue: "ICLR",
    year: 2022,
    quality: "顶会",
    categories: ["memory", "long context"],
    link: "https://arxiv.org/abs/2203.08913",
    summary: "将外部记忆机制引入 Transformer，是长期记忆和可扩展上下文方向的重要代表作。",
  },
  {
    id: "llm-memory-3",
    sectionId: "llm-memory",
    title: "RETRO: Improving Language Models by Retrieving From Trillions of Tokens",
    authors: ["Sebastian Borgeaud", "Arthur Mensch", "Jordan Hoffmann", "Trevor Cai"],
    venue: "DeepMind / arXiv",
    year: 2022,
    quality: "高影响力",
    categories: ["retrieval", "language model"],
    link: "https://arxiv.org/abs/2112.04426",
    summary: "把检索做成语言模型的一等公民，是大规模检索增强建模的重要路线。",
  },
  {
    id: "llm-memory-4",
    sectionId: "llm-memory",
    title: "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection",
    authors: ["Akari Asai", "Zequn Zhang", "Avirup Sil", "Hannaneh Hajishirzi"],
    venue: "ICLR",
    year: 2024,
    quality: "顶会",
    categories: ["RAG", "self-reflection"],
    link: "https://arxiv.org/abs/2310.11511",
    summary: "近一代高质量 RAG 代表作，把检索、生成和反思机制串成一个统一流程。",
  },
  {
    id: "llm-memory-5",
    sectionId: "llm-memory",
    title: "LongMem: Scaling Language Model Context with Memory-Augmented Retrieval",
    authors: ["Zeqiu Wu", "Yizhong Wang", "Jiacheng Liu", "Yelong Shen"],
    venue: "ACL Findings",
    year: 2024,
    quality: "新近代表作",
    categories: ["memory", "long context"],
    link: "https://arxiv.org/abs/2306.07174",
    summary: "把长期记忆和检索结合起来，比较贴近真正可用的记忆库系统设计。",
  },
  {
    id: "llm-memory-6",
    sectionId: "llm-memory",
    title: "MemoRAG: Moving towards Next-Gen RAG Via Memory-Inspired Knowledge Discovery",
    authors: ["Rulin Shao", "Yue Liu", "Shuo Wang", "Yichi Zhang"],
    venue: "arXiv",
    year: 2024,
    quality: "新近代表作",
    categories: ["RAG", "memory bank"],
    link: "https://arxiv.org/abs/2409.05591",
    summary: "更贴近“记忆库”概念的工作，适合关注长期知识积累与调用策略时轮换展示。",
  },

  {
    id: "agents-1",
    sectionId: "agents",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    authors: ["Shunyu Yao", "Jeffrey Zhao", "Dian Yu", "Nan Du"],
    venue: "ICLR",
    year: 2023,
    quality: "顶会",
    categories: ["agent", "reasoning", "tool use"],
    link: "https://arxiv.org/abs/2210.03629",
    summary: "Agent 方向的经典必读，把推理链和行动步骤结合起来，影响极大。",
  },
  {
    id: "agents-2",
    sectionId: "agents",
    title: "Toolformer: Language Models Can Teach Themselves to Use Tools",
    authors: ["Timo Schick", "Jane Dwivedi-Yu", "Roberta Dessì", "Ari Holtzman"],
    venue: "NeurIPS",
    year: 2023,
    quality: "顶会",
    categories: ["tool use", "agent"],
    link: "https://arxiv.org/abs/2302.04761",
    summary: "工具调用主线论文之一，今天很多 function calling 和 agent tool use 都能和它对上脉络。",
  },
  {
    id: "agents-3",
    sectionId: "agents",
    title: "Generative Agents: Interactive Simulacra of Human Behavior",
    authors: ["Joon Sung Park", "Joseph O'Brien", "Carrie Cai", "Meredith Ringel Morris"],
    venue: "UIST",
    year: 2023,
    quality: "顶会",
    categories: ["agent society", "memory"],
    link: "https://arxiv.org/abs/2304.03442",
    summary: "Agent 社会模拟的代表作，对长期记忆、规划和多主体交互都有直接启发。",
  },
  {
    id: "agents-4",
    sectionId: "agents",
    title: "Voyager: An Open-Ended Embodied Agent with Large Language Models",
    authors: ["Guanzhi Wang", "Yuqi Xie", "Zixiang Zhou", "Yujin Tang"],
    venue: "arXiv",
    year: 2023,
    quality: "高影响力",
    categories: ["embodied agent", "planning"],
    link: "https://arxiv.org/abs/2305.16291",
    summary: "把自动课程学习、技能库和持续探索结合起来，是 embodied agent 的代表工作。",
  },
  {
    id: "agents-5",
    sectionId: "agents",
    title: "AutoGen: Enabling Next-Gen LLM Applications via Multi-Agent Conversation",
    authors: ["Qingyun Wu", "Gagan Bansal", "Jiaqi Zhang", "Yiran Wu"],
    venue: "COLM",
    year: 2024,
    quality: "新近代表作",
    categories: ["multi-agent", "framework"],
    link: "https://arxiv.org/abs/2308.08155",
    summary: "多 Agent 协同框架的代表之一，实际工程里也被很多系统直接借鉴。",
  },
  {
    id: "agents-6",
    sectionId: "agents",
    title: "SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering",
    authors: ["John Yang", "Carlos E. Jimenez", "Alexander Wettig", "Karthik Narasimhan"],
    venue: "ICLR",
    year: 2025,
    quality: "新近代表作",
    categories: ["software agent", "benchmark"],
    link: "https://arxiv.org/abs/2405.15793",
    summary: "软件工程 Agent 的代表性论文之一，影响力和可落地性都很强。",
  },
];
